### PR TITLE
1.1.0 Bump... from my account...

### PR DESCRIPTION
**Pull request by kwilcox**

### CODE REVIEW

**Comment by kwilcox** [comment]
:angry:

**Comment by jakirkham** [comment]
Maybe try pushing another commit? If that doesn't do it, we might want to readd this to staged-recipes in case some setting on the feedstock has gotten messed up.

**Comment by synapticarbors** [comment]
So what's the status of this and what needs to be done?

**Comment by jakirkham** [comment]
xref: https://github.com/conda-forge/feedstockrot-feedstock/pull/5

**Pull request closed without merging**
