### PR TITLE
Update to 1.1.0 - take 2

### PR DESCRIPTION
**Pull request by synapticarbors**

### CODE REVIEW

**Comment by synapticarbors** [comment]
@jakirkham -- Closed https://github.com/conda-forge/feedstockrot-feedstock/pull/2 and tried again here, but with the same results. CircleCI seems like it's not being triggered for some reason.

**Comment by jakirkham** [comment]
Every time this has occurred thus far it has been some user setting. Tried to take some guesses last time, but seems like those didn't work. Would comb through the settings on GitHub and CircleCI and try everything you can think of. Sorry I don't have better advice. 😞

**Comment by kwilcox** [comment]
Going to have to re-add to staged-recipes.

**Comment by synapticarbors** [comment]
Any update on doing the re-add or whatever is necessary to get this released? Maybe it would be easier if someone else just copied my original PR and hope that CircleCI like their account better?

**Pull request closed without merging**
