### PR TITLE
Bump to 1.1.0

### PR DESCRIPTION
**Pull request by jochym**

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by jakirkham** [comment]
Could you please review, @kwilcox?

**Comment by kwilcox** [comment]
`noarch` didn't make it into this PR. Was that intentional?

**Comment by synapticarbors** [comment]
@kwilcox you can't have `noarch` if you have version selectors:

https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L25-L28

I'd like to see this merged as it resolves my previous failed attempts in #2 and #3

**Pull request merged**
